name: flutter_application_2
description: A new Flutter project.


publish_to: 'none' 


environment:
  sdk: '>=2.17.0-91.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  cached_network_image: ^3.2.1
  fluttertoast: ^8.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

   uses-material-design: true
  # assets:
  #   - assets/fonts/
  #   - assets/images/

  # fonts:
  #   - family: Billabong
  #     fonts:
  #       - asset: assets/fonts/billabong_font.ttf